name: Infrastructure Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
    AZURE_RESOURCE_GROUP: BCSAI2024-DEVOPS-STUDENTS-B-DEV
    SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
    ALIAS: d4l

jobs:
  lint:         # Lint the Bicep file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: az bicep build --file ./infra/main.bicep --only-show-errors --output json

  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@v3
      # Run Checkov for security scanning
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: './'
        file: 'infra/main.bicep'
      continue-on-error: true

      # Upload Bicep build artifact
    - name: Upload Bicep build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bicep-build
        path: ./infra/main.bicep


  deploy:
    if: github.ref != 'main' && github.event_name == 'push'  || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [build, lint] # skip validate cuz no
    environment:
      name: 'Development'

    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file with Static Web App and other resources
    - name: Deploy Infrastructure (Dev)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./infra/main.bicep
        parameters: ./infra/params.json
        deploymentName: ${{ env.ALIAS }}-dev
        failOnStdErr: false


